[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nb2html_karpatic"
version = "0.0.1"
authors = [
  { name="Charles Karpati", email="charleskarpati@gmail.com" },
]
description = "Convert IPYNB TO HTML"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://cvminigames.com"