# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eazy_ui"
version = "0.0.2"
description = "Make beautifull ui easily"
readme = "README.md"
authors = [{ name = "Sysy's", email = "sysys.owo@gmail.com" }]
keywords = ["easy", "simple", "ui", "checker", "generator"]
dependencies = [
    "requests"
]
requires-python = ">=3"

[project.urls]
Homepage = "https://github.com/Sysys242/Eazy-UI"