[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "video-bot-handle-credits"
version = "0.0.1"
authors = [
  { name="Bruno de Paula", email="bruno.bert.jj@gmail.com" },
]
keywords = ["image", "thumb"]
description = "Handle Credits module"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
   


]

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)

[project.urls]
"Homepage" = "https://github.com/bruno-bert/microservice-handle-credits"