[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "smartez-mq"
version = "0.0.2"
authors = [
  { name="Rune Lykke-Kjeldsen", email="rune@lykke-kjeldsen.dk" },
]
description = "Simple message queue package used for smartez"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.urls]
"Homepage" = "https://github.com/BispensGipsGebis/smartez-mq"
"Bug Tracker" = "https://github.com/BispensGipsGebis/smartez-mq/issues"