[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qparser"
version = "0.1a3"
authors = [
    { name = "@bbc6502", email = "c0d3@gpobox.net" }
]
description = "Query Parser"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/bbc6502/qparser"
"Bug Tracker" = "https://github.com/bbc6502/qparser/issues"
