[tool.poetry]
name = "bluetarget"
version = "0.3.1"
description = "Deploy, monitor and explain your machine learning models"
authors = ["Sergio Kaz <sergio@bluetarget.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"
click = ">=8.0"
requests = ">=2.27"
pyarrow =">=7.0"
pydantic = ">=1.9"
pandas = ">=1.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
