[tool.poetry]
name        = "src2prod"
version     = "0.1.0-beta"
description = 'This module allows to develop a project within a source folder and to publish the final product in another folder, this last directory being a "thin" version of the source one.'
readme       = "README.md"
authors      = ["Christophe BAL"]
maintainers  = ["Christophe BAL"]
license      = "GNU License Version 3"
repository   = "https://github.com/bc-tools/for-dev/tree/main/src2prod"

[tool.poetry.dependencies]
python  = "^3.8"
click   = "^7.1.2"
multimd = "^0.1.0-beta.0"
spkpb   = "^0.0.10-beta.0"

[tool.poetry.dev-dependencies]

[build-system]
requires      = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
src2prod = "src2prod.cmdline:update"
