[tool.poetry]
name = "starfield"
version = "0.1.2"
description = ""
authors = ["IsaacBreen <57783927+IsaacBreen@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "starfield"}]

[tool.poetry.dependencies]
python = "^3.9"
attrs = "^22.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
pytest-codeblocks = "^0.16.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--codeblocks"