[tool.mypy]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.scriv]
categories = "Removed, Added, Changed, Deprecated, Fixed, Security"
format = "rst"
version = "literal: pyproject.toml: tool.poetry.version"

[tool.pycln]
all = true

[tool.poetry]
name = "mastodonamnesia"
version = "2.0.3"
description = "deletes old Mastodon toots"
authors = ["marvin8 <marvin8@tuta.io>"]
license = "AGPL-3.0-or-later"
readme = "README.rst"
repository = "https://codeberg.org/MarvinsMastodonTools/mastodonamnesia"

[tool.poetry.urls]
"Changelog" = "https://codeberg.org/MarvinsMastodonTools/mastodonamnesia/src/branch/main/CHANGELOG.rst"

[tool.poetry.scripts]
mastodonamnesia = "mastodonamnesia.mastodon_amnesia:start"

[[tool.poetry.source]]
name = "masto-tools-dev"
url = "https://codeberg.org/api/packages/MarvinsMastodonTools/pypi/simple"
default = false
secondary = true

[tool.poetry_bumpversion.file."src/mastodonamnesia/__init__.py"]

[tool.poetry.dependencies]
python = "^3.9"
arrow = "^1.2.1"
rich = "^12.0.0"
typing-extensions = "^4.2.0"
outdated = "^0.2.1"
tqdm = "^4.64.0"
aiofiles = "^0.8.0"
minimal-activitypub = "^0.4.0"

[tool.poetry.group.dev.dependencies]
dlint = "^0.13.0"
pre-commit = "^2.16.0"
pylint = "^2.14.5"
flake8 = "^5.0.4"
black = "^22.1.0"
flake8-eradicate = "^1.2.0"
mypy = "^0.991"
tomli = "^2.0.1"
flake8-bugbear = "^22.1.11"
pep8-naming = "^0.13.1"
flake8-black = "^0.3.2"
flake8-import-order = "^0.18.1"
bandit = "^1.7.4"
safety = "^2.1.1"
flake8-annotations = "^2.9.0"
pip-audit = "^2.4.3"
coverage = "^6.4.4"
packaging = "^22.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
